<?php

namespace App\Repositories\Admin;

use App\Admin;
use App\Menu;
use App\Repositories\Repository;
use Illuminate\Http\Request;

class AdminsRepository extends Repository
{
    protected $model;

    public function __construct(Admin $model)
    {
        $this->model = $model;
    }

    public function all($attributes='')
    {
        return $this->model::all();
    }

    public function create($attributes)
    {
        try{
            $attributes = array_merge($attributes, [
                'no' => 'a'.auth()->guard('admin')->user()->id. time().rand('00','99'), //以時間當亂數種子
                'createIP' => getUserIpAddr(),
                'active' => 1,
                'remember_token' =>  str_random(10),
            ]);
            return parent::create($attributes); // TODO: Change the autogenerated stub
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function update($attributes, $id)
    {
        try{
            $attributes = array_merge($attributes, [
                'no' => 'a'. auth()->guard('admin')->user()->id. time(). rand('00','99'), //以時間當亂數種子
                'createIP' => getUserIpAddr(),
//                'active' => 1,
//                'remember_token' =>  str_random(10),
            ]);
            return parent::update($attributes, $id);
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function delete($id)
    {
        return parent::delete($id);
    }
}
