<?php

namespace App\Repositories\Admin;

use App\Admin;
use App\AdminMenu;
use App\Menu;
use App\Permission;
use App\Repositories\Repository;

class MenuRepository extends Repository
{
    protected $model;

    public function __construct(Menu $model)
    {
        $this->model = $model;
    }

    public function setModel_AdminMenu()
    {
        $this->model = new AdminMenu;
    }

    public function all($attributes='')
    {
        return $this->model::all();
    }

    public function create($attributes)
    {
        try{
            $attributes = array_merge($attributes, [
                'author_id' => auth()->guard('admin')->user()->id,
                'open' => 1,
            ]);
            return parent::create($attributes); // TODO: Change the autogenerated stub
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function update($attributes, $id)
    {
        try{
            $attributes = array_merge($attributes, [
                'author_id' => auth()->guard('admin')->user()->id,
            ]);
            // 啟用 或 不啟用
            if (isset($attributes['open'])) {
                $admin_menu = $this->model->find($id);
                $attributes['open'] = ($attributes['open'] == "change") ? !$admin_menu->open : $admin_menu->open;
            }

            return parent::update($attributes, $id);
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function delete($id)
    {
        return parent::delete($id);
    }


    /*
     * data object or array forEach to do.
     */
    public function eachOne_aaData($arr)
    {
        if ( $arr['aaData']) {
            foreach ($arr['aaData'] as $key => $var) {
                $var->Title = trans('menu.'. $var->name. '.title');
            }
        }
        return $arr;
    }
    /* data object or array forEach to do. for admin_menu */
    public function eachOne_aaData_adminMenu($arr)
    {
        if ( $arr['aaData']) {
            foreach ($arr['aaData'] as $key => $var) {
                //
                $admin = Admin::query()->find($var->admin_id);
                $var->admin_name = $admin->name;
                $var->admin_type = $admin->type;
                //
                $menu = Menu::query()->find($var->menu_id);
                $var->menu_name = trans('menu.'. $menu->name. '.title');
            }
        }
        return $arr;
    }
}
