<?php

namespace App\Repositories\Admin;

use App\Http\Controllers\FuncController;
use App\Product;
use App\ProductCategory;
use App\ProductCombination;
use App\ProductSpec;
use App\Repositories\Repository;


class ProductRepository extends Repository
{
    protected $model;

    public function __construct(Product $model)
    {
        $this->model = $model;
    }

    public function setModel_ProductSpec()
    {
        $this->model = new ProductSpec();
    }

    public function setModel_ProductCategore()
    {
        $this->model = new ProductCategory();
    }

    public function setModel_Product()
    {
        $this->model = new Product();
    }

    public function setModel_ProductCombination()
    {
        $this->model = new ProductCombination();
    }

    public function getORM_ProductCategory($columns = ['*'], $whereQuery='1 = 1')
    {
        return ProductCategory::query()->where('open', 1)->whereRaw($whereQuery)->orderBy('rank', 'asc')->get($columns);
    }

    public function getORM_Product($columns = ['*'], $whereQuery='1 = 1')
    {
        return Product::query()->whereRaw($whereQuery)->orderBy('rank', 'asc')->with('category', 'spec')->get($columns);
    }

    public function create($attributes, $from='product')
    {
        try{
            if ($from=='product') {
                $attributes = array_merge($attributes, [
                    'no' => 'GP' . date('Ymd') . rand(1001, 9999),
                    'author_id' => auth()->guard('admin')->user()->id,
                    'open' => config('app.open_default', 1),
                    'rank' => 5,
                ]);
                $attributes['price'] = data_get($attributes, 'price') ?: '100';
                $attributes['product_description'] = htmlspecialchars( data_get($attributes, 'product_description') ?: '' );
                $attributes['service_description'] = htmlspecialchars( data_get($attributes, 'service_description') ?: '' );
            }
            if ($from=='product_combinations') {
                $attributes = array_merge($attributes, [
                    'no' => 'PC' . date('Ymd') . rand(1001, 9999),
                    'author_id' => auth()->guard('admin')->user()->id,
                    'open' => 0,//config('app.open_default', 1),
                    'rank' => 5,
                ]);
                $attributes['price'] = data_get($attributes, 'price') ?: '500';
            }
            return parent::create($attributes); // TODO: Change the autogenerated stub
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function update($attributes, $id)
    {
        try{
            $attributes = array_merge($attributes, [
                'author_id' => auth()->guard('admin')->user()->id,
            ]);
            // 啟用 或 不啟用
            if (isset($attributes['open']) && isset($attributes['doValidate'])) {
                $scene = $this->model->find($id);
                $attributes['open'] = ($attributes['open'] == "change") ? !$scene->open : $scene->open;
            }
            //
            if (isset($attributes['product_description']) /*&& isset($attributes['doValidate'])*/) {
                $attributes['product_description'] = htmlspecialchars( $attributes['product_description']);
            }
            if (isset($attributes['service_description']) /*&& isset($attributes['doValidate'])*/) {
                $attributes['service_description'] = htmlspecialchars( $attributes['service_description']);
            }

            return parent::update($attributes, $id);
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }

    public function delete($id, $onDelete='', $for='')
    {
        try{
            $model = parent::delete($id);

            if ($onDelete=='cascade') {
                if ($for == 'product_spec') {
                    /* 刪除商品，商品下規格也刪除
                      $table->foreign('product_specs.product_id')->references('product.id')->on('product')->onDelete('cascade');
                     */
                    $this->setModel_ProductSpec();
                    $model = $this->model->where('product_id', $id)->delete();
                    $str = 'product_id='.$id;
                } else {
                    /* 刪除商品類別，類別下商品也刪除
                      $table->foreign('product.type')->references('product_categories.id')->on('product_categories')->onDelete('cascade');
                     */
                    $this->setModel_Product();
                    $model = $this->model->where('type', $id)->delete();
                    $str = 'type='.$id;
                }
                $author_id = auth()->guard('admin')->user()->id;
                $value = json_encode( $model, JSON_UNESCAPED_UNICODE);
                FuncController::addActionLog('delete', $author_id, $value, $str, $this->model->getTable() );
            }

            return $model;
        } catch (\Exception $e){
            return ['errors'=> $e->getMessage()];
        }
    }
}
