<?php
return [
    'mail' =>
        [
          'ttb' =>
            [
                'address' => 'ronghong@kahap.com'
            ],
        ],
    'admin_access' => [ 1, 2 ],
    'activity' => [
        'coin' => [
            'register_time' => 86400 * 30 * 3,
            'login_time' => 86400 * 30 * 3
        ]
    ],
    'coin_fee' => 0.1,
    'agent_code' => "kahap",
    'center_connection' => env( 'DB_CENTER_CONNECTION' ),
    'fb_appid' => env( 'FB_APPID' ),
    'fb_secret' => env( 'FB_SECRET' ),
    'fb_ver' => env( 'FB_VER' ),
    'g_plus_client_id' => env( 'G_PLUS_CLIENT_ID' ),
    'g_plus_client_pw' => env( 'G_PLUS_CLIENT_PW' ),
    'mall_connection' => env( 'DB_CONNECTION' ),
    'order_limit_time' => env( 'ORDER_LIMIT_TIME' ),
    'order_num_header' => env( 'ORDER_NUM_HEADER', 'TTW' ),
    'order_pay_status' =>
        [
            '0' => '未付款',
            '1' => '已付款',
            '2' => '已取消授權',
            '3' => '已退款',
            '11' => '已取號',
            '99' => '付款失敗',
        ],
    'order_status' =>
        [
            '0' => '尚未處理',
            '1' => '訂單已完成',
            '2' => '訂單已取消',
            '3' => '處理中',
            '4' => '處理中',
            '5' => '已出貨',
            '6' => '待提貨',
        ],
    'productType' => [
        'museum_a01' => 201,
        'museum_a02' => 202,
        'museum_a03' => 203,
        'museum_a04' => 204,
        'museum_a05' => 205,
        'museum_a06' => 206,
        'museum_a07' => 207,
        'museum_a08' => 208,
        'museum_a09' => 209,
        'museum_a10' => 210,
        'museum_a11' => 211,
        'museum_a12' => 212,
    ],
    'sys_category' => [
        'product' => [
            'type' => 1,
            'pid' => 1,
        ],
        'pay' => [
            'type' => 2,
            'pid' => 2,
        ],
        'news' => [
            'type' => 3,
            'pid' => 3,
        ],
        'activity' => [
            'type' => 4,
            'pid' => 4,
        ],
        'museum' => [
            'type' => 5,
            'pid' => 5,
        ],
    ],
    'verification' =>
        [
            'limit' => 12,
            'time' => 3600,
        ],


    'str_num' =>
        [
            'A' => '01',
            'B' => '02',
            'C' => '03',
            'D' => '04',
            'E' => '05',
            'F' => '06',
            'G' => '07',
            'H' => '08',
            'I' => '09',
            'J' => '10',
            'K' => '11',
            'L' => '12',
            'M' => '13',
            'N' => '14',
            'O' => '15',
            'P' => '16',
            'Q' => '17',
            'R' => '18',
            'S' => '19',
            'T' => '20',
            'U' => '21',
            'V' => '22',
            'W' => '23',
            'X' => '24',
            'Y' => '25',
            'Z' => '26'
        ],
    'weekly' =>
        [
            '1' => '一',
            '2' => '二',
            '3' => '三',
            '4' => '四',
            '5' => '五',
            '6' => '六',
            '0' => '日'
        ],
    'str_arr' =>
        [
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            //'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            //'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z'
        ],
    'global_keyword' => [
        'admin.logout' => '登出,logout,exit,',
        'admins.create' => '創建管理者,新增管理者,新建管理,新管理,新使用者,加入管理者,create admins,admin create,add admins,new admins',
        'admins.index' => '管理者列表,後台管理員,後臺管理員,admins,manager,administration',
        'admins.edit:no' => '修改基本資料,更改我的資料,修改我的資料,更改密碼,My Profile,My profile,my profile,',
        'admin_permission.create' => '創建權限,新權限,新增權限,加入權限,加權限,create permissions,permission create,add permissions,new permissions',
        'admin_permission.index' => '權限列表,後台權限管理,管理權限,permissions list,all permissions,',
        'permissions.create' => '創建權限,新權限,新增權限,加入權限,加權限,create permissions,permission create,add permissions,new permissions',
        'permissions.index' => '權限列表,後台權限管理,管理權限,permissions list,all permissions,',
        'admin_menu.create' => '創建選項,新選項,新增選項,加入選項,加選項,create menus,menu create,add menus,new menus',
        'admin_menu.index' => '選項列表,後台選項管理,管理選項,menus list,all menus,',
        'menus.create' => '創建選項,新選項,新增選項,加入選項,加選項,create menus,menu create,add menus,new menus',
        'menus.index' => '選項列表,後台選項管理,管理選項,menus list,all menus,',
        
        'group.member.index' => '會員群組管理,會員群組列表管理,group member list,groups',
        'group.member.create' => '創建會員群組,新會員群組,新增會員群組,加入會員群組,加會員群組,create group members,members group create,add group members,new group members',
        'group.store.index' => '店家群組管理,店家群組列表管理,group store list',
        'group.store.create' => '創建店家群組,新店家群組,新增店家群組,加入店家群組,加店家群組,create group stores,store group create,add group stores,new group stores',
        'group.supplier.index' => '供應商群組管理,供應商群組列表管理,group supplier list',
        'group.supplier.create' => '創建供應商群組,新供應商群組,新增供應商群組,加入供應商群組,加供應商群組,create group suppliers,suppliers group create,add group suppliers,new group suppliers',
        'group.admin.index' => '管理員群組管理,管理員群組列表管理,group admin list',
        'group.admin.create' => '創建管理員群組,新管理員群組,新增管理員群組,加入管理員群組,加管理員群組,create group admins,admin group create,add group admins,new group admins',
        
        'category.index' => '系統類別管理,系統類別列表管理,category list,category',
        'category.create' => '創建系統類別,新系統類別,新增系統類別,加入系統類別,加系統類別,create categories,category create,add categories,new categories',
        
        'store.index' => '商店店家管理,商店店家列表管理,store list,stores',
        'store.create' => '創建商店店家,新商店店家,新增商店店家,加入商店店家,加商店店家,create stores,store create,add stores,new stores',
        'supplier.index' => '供應商管理,供應商列表管理,supplier list,suppliers',
        'supplier.create' => '創建供應商,新供應商,新增供應商,加入供應商,加供應商,create suppliers,supplier create,add suppliers,new suppliers',

        'articles.index' => '文章管理,文章列表管理,article list,articles',
        'articles.create' => '創建文章,新文章,新增文章,加入文章,加文章,create articles,article create,add articles,new articles',
        
        'information.announce.index' => '公告管理,公告列表管理,announce list,announces',
        'information.announce.create' => '創建公告,新公告,新增公告,加入公告,加公告,create announces,announces create,add announces,new announces',
        'information.news.index' => '最新消息管理,最新消息列表管理,news list,news',
        'information.news.create' => '創建最新消息,新最新消息,新增最新消息,加入最新消息,加最新消息,create news,news create,add news,new news',
        'information.messages.index' => '訊息管理,訊息列表管理,message list,messages',
        'information.messages.create' => '創建訊息,新訊息,新增訊息,加入訊息,加訊息,create messages,message create,add messages,new messages',
        'information.reports.index' => '媒體報導管理,媒體報導列表管理,report list,reports',
        'information.reports.create' => '創建媒體報導,新媒體報導,新增媒體報導,加入媒體報導,加媒體報導,create reports,report create,add reports,new reports',
        'information.notifications.index' => '通知管理,通知列表管理,notification list,notifications',
        'information.notifications.create' => '創建通知,新通知,新增通知,加入通知,加通知,create notifications,notification create,add notifications,new notifications',

        'product.category.index' => '商品類別管理,商品類別列表管理,category list,categories',
        'product.category.create' => '創建商品類別,新商品類別,新增商品類別,加入商品類別,加商品類別,create categories,categories create,add categories,new categories',
        'product.manage.index' => '商品管理,商品列表管理,product list,products',
        'product.manage.create' => '創建商品,新商品,新增商品,加入商品,加商品,create products,product create,add products,new products',
        'product.spec.index' => '商品規格管理,商品規格列表管理,spec list,spec',
        'product.spec.create' => '創建商品規格,新商品規格,新增商品規格,加入商品規格,加商品規格,create spec,spec create,add spec,new spec',
        'product.combinations.index' => '組合商品管理,組合商品列表管理,combination list,combinations',
        'product.combinations.create' => '創建組合商品,新組合商品,新增組合商品,加入組合商品,加組合商品,create combinations,combination create,add combinations,new combinations',
        'product.shipping.index' => '運費管理,運費列表管理,shipping list,shipping',
        'product.shipping.create' => '創建運費,新運費,新增運費,加入運費,加運費,create shipping,shipping create,add shipping,new shipping',
        'product.pay.index' => '付款方式管理,付款方式列表管理,pay list,pay',
        'product.pay.create' => '創建付款方式,新付款方式,新增付款方式,加入付款方式,加付款方式,create pay,pay create,add pay,new pay',

        'order.product.index' => '商品訂單管理,商品訂單列表管理,order list,orders',
        'order.product.create' => '創建商品訂單,新商品訂單,新增商品訂單,加入商品訂單,加商品訂單,create orders,order create,add orders,new orders',
        'order.detail.index' => '訂單詳情管理,訂單詳情列表管理,訂單明細管理,訂單明細列表管理,order detail list,order details',
        'order.detail.create' => '創建訂單詳情,新訂單詳情,新增訂單詳情,加入訂單詳情,加訂單詳情,create order details,order detail create,add order details,new order details',
        'order.contact.index' => '訂單寄送地址管理,訂單寄送地址列表管理,order contact list,order contacts',
        'order.contact.create' => '創建訂單寄送地址,新訂單寄送地址,新增訂單寄送地址,加入訂單寄送地址,加訂單寄送地址,create order contacts,order contact create,add order contacts,new order contacts',
        
        'scenes.navbar.index' => '前台選項欄位,前台選單欄位,場景選項欄位,背景選項欄位,scenes navbar list,navbars',
        'scenes.navbar.create' => '創建選項,新選項,新增選項,加入選項,加選項,create navbars,navbar create,add navbars,new navbars',
        'scenes.slider.index' => '前台滑動圖欄位,前台廣告圖欄位,場景滑動圖欄位,背景滑動圖欄位,scenes sliders list,banners list',
        'scenes.slider.create' => '創建滑動圖,新滑動圖,新增滑動圖,加入滑動圖,加滑動圖,create sliders,slider create,add sliders,new sliders',
        'scenes.introduce.index' => '前台文字介紹欄位,前台文字內文欄位,場景文字介紹欄位,背景文字介紹欄位,scenes introduces list,contents,details,summarys',
        'scenes.introduce.create' => '創建文字介紹,新文字介紹,新增文字介紹,加入文字介紹,加文字介紹,create introduces,introduce create,add introduces,new introduces',
        'scenes.image.index' => '前台圖片欄位,前台照片欄位,場景圖片欄位,背景圖片欄位,scenes images list,pictures',
        'scenes.image.create' => '創建圖片,新圖片,新增圖片,加入圖片,加圖片,create images,image create,add images,new images',
        'scenes.footer.index' => '前台腳板欄位,前台底塊欄位,場景腳板欄位,背景腳板欄位,scenes footers list',
        'scenes.footer.create' => '創建腳板,新腳板,新增腳板,加入腳板,加腳板,create footer,scenes footer create,add footer,new footer',

        'setting.search_keywords.index' => '前台搜尋關鍵字欄位,前台搜尋關鍵詞欄位,場景搜尋關鍵字欄位,背景搜尋關鍵字欄位,search keywords list',
        'setting.search_keywords.create' => '創建搜尋關鍵字,新搜尋關鍵字,新增搜尋關鍵字,加入搜尋關鍵字,加搜尋關鍵字,create search keywords,search keyword create,add search keywords,new search keywords',
        'setting.parameters.index' => '前台系統參數欄位,前台選單欄位,場景系統參數欄位,背景系統參數欄位,parameters list,setting list',
        'setting.parameters.create' => '創建系統參數,新系統參數,新增系統參數,加入系統參數,加系統參數,create parameters,menu parameters,add parameters,new parameters',
        'setting.parameter.global_keyword.index' => '後台搜尋字詞欄位,後台選單欄位,場景搜尋字詞欄位,背景搜尋字詞欄位,global search list,global keyword list',
        'setting.parameter.global_keyword.create' => '創建搜尋字詞,新搜尋字詞,新增搜尋字詞,加入搜尋字詞,加搜尋字詞,create global keyword,global keyword create,add global keyword,new global keyword',
    ],
];
